server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # Eureka не должна регистрировать себя (оставляем false)
    fetch-registry: false         # Но Eureka должна уметь отдавать зарегистрированные сервисы
  server:
    enable-self-preservation: false  # (Отключаем "самозащиту", чтобы сразу удалять неактивные сервисы)
    eviction-interval-timer-in-ms: 5000  # (Чистим мертвые инстансы каждые 5 секунд)
