server:
  port: 8003

spring:
  application:
    name: template-service

  datasource:
    url: jdbc:postgresql://localhost:5432/Sensa_Template_Service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true

  jpa:
    hibernate:
      ddl-auto: validate

# Swagger UI
springdoc:
  api-docs:
    path: /template-service/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
