server:
  port: 8004

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/Sensa_Notification_Service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
    topics:
      notifications:
        email: notification-service-to-message-delivery-service-mail
        sms: notification-service-to-message-delivery-service-sms

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /notification-service/api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: method

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true

services:
  template-service:
    url: http://localhost:8003
  user-management-service:
    url: http://localhost:8000