version: '3.8'

services:
  message-delivery-service:
    build: .
    image: message-delivery-service:latest
    container_name: message-delivery-service
    ports:
      - "8005:8005"
    environment:
      KAFKA_BROKERS: kafka:9092
      CONSUMER_GROUP: message-delivery-service
      DELIVERY_TOPIC: notification.delivery
      SERVER_PORT: "8005"
      RUST_LOG: info
    depends_on:
      - zookeeper
      - kafka
    networks:
      - sensa-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: message-delivery-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2184:2181"
    networks:
      - sensa-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: message-delivery-kafka
    depends_on:
      - zookeeper
    ports:
      - "9095:9092"
    environment:
      KAFKA_BROKER_ID: 4
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - sensa-network

networks:
  sensa-network:
    driver: bridge
