version: '3.8'

services:
  template-service:
    build: .
    image: template-service:latest
    container_name: template-service
    ports:
      - "8003:8003"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 28859013
      JWT_USER_SECRET: "change-me"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
    depends_on:
      - postgres
    networks:
      - sensa-network

  postgres:
    image: postgres:15.2
    container_name: template-postgres
    environment:
      POSTGRES_DB: Sensa_Template_Service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 28859013
    ports:
      - "5434:5432"
    networks:
      - sensa-network

networks:
  sensa-network:
    driver: bridge
