version: '3.8'

services:
  authentication-service:
    build: .
    image: authentication-service:latest
    container_name: authentication-service
    ports:
      - "8001:8001"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 28859013
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://my-eureka-server-host:8761/eureka"
      JWT_USER_SECRET: "change-me"
    depends_on:
      - postgres
      - zookeeper
      - kafka
    networks:
      - sensa-network

  postgres:
    image: postgres:15.2
    container_name: auth-postgres
    environment:
      POSTGRES_DB: Sensa_Authentication_Service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 28859013
    ports:
      - "5432:5432"
    networks:
      - sensa-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - sensa-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - sensa-network

networks:
  sensa-network:
    driver: bridge
