spring:
  application:
    name: user-management-service

  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/Sensa_User_Management_Service
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    consumer:
      group-id: user-management-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true

server:
  port: 8000

springdoc:
  api-docs:
    path: /user-management-service/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
