spring:
  application:
    name: user-data-management-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/Sensa_User_Data_Management_Service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092

  redis:
    host: localhost
    port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true

server:
  port: 8000

springdoc:
  api-docs:
    path: /user-data-management-service/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
