CREATE SEQUENCE IF NOT EXISTS user_seq START 1 INCREMENT 1;

CREATE TABLE authentication_user(
    id BIGINT PRIMARY KEY DEFAULT nextval('user_seq'),
    user_id UUID NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);
